<?php

namespace Database\Seeders;

use App\Models\Event;
use Illuminate\Database\Seeder;

class EventSeeder extends Seeder
{
    public function run(): void
    {
        Event::truncate();

        $events = [
            // ── Passados ──────────────────────────────────────────────────────
            [
                'date' => '2023-09-16',
                'title' => 'PHP Conference Brasil 2023',
                'type' => 'conf',
                'org' => 'PHP Conference Brasil',
                'time' => '09h00 – 18h00',
                'location' => 'São Paulo, SP',
                'is_online' => false,
                'status' => 'full',
                'cta_label' => 'Ver gravações',
                'cta_style' => 'ghost',
                'cta_url' => 'https://phpconference.com.br',
                'seats' => null,
                'seats_low' => false,
            ],
            [
                'date' => '2023-11-04',
                'title' => 'Laravel Meetup SP — Novembro 2023',
                'type' => 'meetup',
                'org' => 'Laravel São Paulo',
                'time' => '14h00 – 17h00',
                'location' => 'São Paulo, SP',
                'is_online' => false,
                'status' => 'full',
                'cta_label' => null,
                'cta_style' => 'ghost',
                'cta_url' => null,
                'seats' => null,
                'seats_low' => false,
            ],
            [
                'date' => '2024-02-17',
                'title' => 'React Summit Online — Edição de Inverno',
                'type' => 'conf',
                'org' => 'GitNation',
                'time' => '11h00 – 19h00',
                'location' => 'Transmissão ao vivo',
                'is_online' => true,
                'status' => 'full',
                'cta_label' => 'Assistir replay',
                'cta_style' => 'ghost',
                'cta_url' => 'https://reactsummit.com',
                'seats' => null,
                'seats_low' => false,
            ],
            [
                'date' => '2024-04-20',
                'title' => 'Hackathon Open Source Brasil',
                'type' => 'hack',
                'org' => 'OpenDevs BR',
                'time' => '08h00 – 20h00',
                'location' => 'Belo Horizonte, MG',
                'is_online' => false,
                'status' => 'full',
                'cta_label' => null,
                'cta_style' => 'ghost',
                'cta_url' => null,
                'seats' => null,
                'seats_low' => false,
            ],
            [
                'date' => '2024-07-06',
                'title' => 'TDC Innovation 2024',
                'type' => 'conf',
                'org' => 'The Developer\'s Conference',
                'time' => '08h00 – 18h00',
                'location' => 'São Paulo, SP',
                'is_online' => false,
                'status' => 'full',
                'cta_label' => 'Ver palestras',
                'cta_style' => 'ghost',
                'cta_url' => 'https://thedevconf.com',
                'seats' => null,
                'seats_low' => false,
            ],
            [
                'date' => '2024-09-28',
                'title' => 'Workshop: CI/CD com GitHub Actions',
                'type' => 'workshop',
                'org' => 'DevOps Academy BR',
                'time' => '09h00 – 13h00',
                'location' => 'Transmissão ao vivo',
                'is_online' => true,
                'status' => 'full',
                'cta_label' => null,
                'cta_style' => 'ghost',
                'cta_url' => null,
                'seats' => null,
                'seats_low' => false,
            ],
            [
                'date' => '2024-11-16',
                'title' => 'Hackathon IA para Devs',
                'type' => 'hack',
                'org' => 'AI Builders BR',
                'time' => '08h00 – 22h00',
                'location' => 'Curitiba, PR',
                'is_online' => false,
                'status' => 'full',
                'cta_label' => null,
                'cta_style' => 'ghost',
                'cta_url' => null,
                'seats' => null,
                'seats_low' => false,
            ],
            [
                'date' => '2025-01-25',
                'title' => 'Workshop: APIs REST com Laravel Sanctum',
                'type' => 'workshop',
                'org' => 'DevLab Brasil',
                'time' => '09h00 – 13h00',
                'location' => 'Transmissão ao vivo',
                'is_online' => true,
                'status' => 'full',
                'cta_label' => 'Ver repositório',
                'cta_style' => 'ghost',
                'cta_url' => null,
                'seats' => null,
                'seats_low' => false,
            ],
            [
                'date' => '2025-03-08',
                'title' => 'React Summit Brasil 2025',
                'type' => 'conf',
                'org' => 'GitNation',
                'time' => '09h00 – 18h00',
                'location' => 'São Paulo, SP',
                'is_online' => false,
                'status' => 'full',
                'cta_label' => 'Ver gravações',
                'cta_style' => 'ghost',
                'cta_url' => 'https://reactsummit.com',
                'seats' => null,
                'seats_low' => false,
            ],
            [
                'date' => '2025-05-10',
                'title' => 'Laravel Meetup SP — Maio 2025',
                'type' => 'meetup',
                'org' => 'Laravel São Paulo',
                'time' => '14h00 – 17h30',
                'location' => 'São Paulo, SP',
                'is_online' => false,
                'status' => 'full',
                'cta_label' => null,
                'cta_style' => 'ghost',
                'cta_url' => null,
                'seats' => null,
                'seats_low' => false,
            ],
            [
                'date' => '2026-04-18',
                'title' => 'PHP Conference Brasil 2026',
                'type' => 'conf',
                'org' => 'PHP Conference Brasil',
                'time' => '09h00 – 18h00',
                'location' => 'São Paulo, SP',
                'is_online' => false,
                'status' => 'full',
                'cta_label' => 'Ver gravações',
                'cta_style' => 'ghost',
                'cta_url' => 'https://phpconference.com.br',
                'seats' => null,
                'seats_low' => false,
            ],
            [
                'date' => '2026-05-09',
                'title' => 'Hackathon Sustentabilidade Tech 2026',
                'type' => 'hack',
                'org' => 'GreenTech Brasil',
                'time' => '08h00 – 22h00',
                'location' => 'Curitiba, PR',
                'is_online' => false,
                'status' => 'full',
                'cta_label' => null,
                'cta_style' => 'ghost',
                'cta_url' => null,
                'seats' => null,
                'seats_low' => false,
            ],

            // ── Futuros ───────────────────────────────────────────────────────
            [
                'date' => '2026-07-11',
                'title' => 'Workshop: Inertia.js + React do Zero',
                'type' => 'workshop',
                'org' => 'DevLab Brasil',
                'time' => '09h00 – 13h00',
                'location' => 'Transmissão ao vivo',
                'is_online' => true,
                'status' => 'open',
                'cta_label' => 'Garantir vaga',
                'cta_style' => 'primary',
                'cta_url' => 'https://devlab.com.br/inertia-react',
                'seats' => 'Vagas disponíveis',
                'seats_low' => false,
            ],
            [
                'date' => '2026-07-25',
                'title' => 'Laravel Meetup SP — Julho 2026',
                'type' => 'meetup',
                'org' => 'Laravel São Paulo',
                'time' => '14h00 – 17h30',
                'location' => 'São Paulo, SP',
                'is_online' => false,
                'status' => 'open',
                'cta_label' => 'Confirmar presença',
                'cta_style' => 'primary',
                'cta_url' => 'https://meetup.com/laravel-sp',
                'seats' => '42 vagas restantes',
                'seats_low' => false,
            ],
            [
                'date' => '2026-08-08',
                'title' => 'Hackathon Dev + IA 2026',
                'type' => 'hack',
                'org' => 'AI Builders BR',
                'time' => '08h00 – 22h00',
                'location' => 'São Paulo, SP',
                'is_online' => false,
                'status' => 'open',
                'cta_label' => 'Inscrever equipe',
                'cta_style' => 'primary',
                'cta_url' => 'https://hackathon.aibuilders.com.br',
                'seats' => '30 equipes disponíveis',
                'seats_low' => false,
            ],
            [
                'date' => '2026-08-22',
                'title' => 'Workshop: Testes Automatizados no Laravel',
                'type' => 'workshop',
                'org' => 'DevLab Brasil',
                'time' => '10h00 – 14h00',
                'location' => 'Transmissão ao vivo',
                'is_online' => true,
                'status' => 'open',
                'cta_label' => 'Garantir vaga',
                'cta_style' => 'primary',
                'cta_url' => 'https://devlab.com.br/laravel-tests',
                'seats' => 'Vagas disponíveis',
                'seats_low' => false,
            ],
            [
                'date' => '2026-09-05',
                'title' => 'TDC Innovation 2026',
                'type' => 'conf',
                'org' => 'The Developer\'s Conference',
                'time' => '08h00 – 18h00',
                'location' => 'São Paulo, SP',
                'is_online' => false,
                'status' => 'open',
                'cta_label' => 'Comprar ingresso',
                'cta_style' => 'primary',
                'cta_url' => 'https://thedevconf.com',
                'seats' => 'Vagas disponíveis',
                'seats_low' => false,
            ],
            [
                'date' => '2026-09-19',
                'title' => 'Meetup Backend Brasil — Setembro 2026',
                'type' => 'meetup',
                'org' => 'Backend Brasil',
                'time' => '15h00 – 18h00',
                'location' => 'Transmissão ao vivo',
                'is_online' => true,
                'status' => 'open',
                'cta_label' => 'Inscrever-se',
                'cta_style' => 'primary',
                'cta_url' => 'https://backendbrasilmeetup.com.br',
                'seats' => 'Vagas ilimitadas',
                'seats_low' => false,
            ],
            [
                'date' => '2026-10-10',
                'title' => 'Workshop: Docker e Kubernetes para Devs',
                'type' => 'workshop',
                'org' => 'DevOps Academy BR',
                'time' => '09h00 – 17h00',
                'location' => 'Rio de Janeiro, RJ',
                'is_online' => false,
                'status' => 'open',
                'cta_label' => 'Garantir vaga',
                'cta_style' => 'primary',
                'cta_url' => 'https://devopsacademy.com.br/docker-k8s',
                'seats' => '20 vagas',
                'seats_low' => false,
            ],
            [
                'date' => '2026-10-24',
                'title' => 'Laravel Meetup SP — Outubro 2026',
                'type' => 'meetup',
                'org' => 'Laravel São Paulo',
                'time' => '14h00 – 17h30',
                'location' => 'São Paulo, SP',
                'is_online' => false,
                'status' => 'soon',
                'cta_label' => 'Entrar na lista de espera',
                'cta_style' => 'ghost',
                'cta_url' => 'https://meetup.com/laravel-sp',
                'seats' => 'Últimas vagas',
                'seats_low' => true,
            ],
            [
                'date' => '2026-11-07',
                'title' => 'Hackathon Fintech Open 2026',
                'type' => 'hack',
                'org' => 'Fintech Hub BR',
                'time' => '08h00 – 22h00',
                'location' => 'São Paulo, SP',
                'is_online' => false,
                'status' => 'soon',
                'cta_label' => 'Entrar na fila',
                'cta_style' => 'ghost',
                'cta_url' => 'https://hackathon.fintechhub.com.br',
                'seats' => '5 vagas restantes',
                'seats_low' => true,
            ],
            [
                'date' => '2026-11-21',
                'title' => 'Workshop: Performance em Apps React',
                'type' => 'workshop',
                'org' => 'DevLab Brasil',
                'time' => '09h00 – 13h00',
                'location' => 'Transmissão ao vivo',
                'is_online' => true,
                'status' => 'open',
                'cta_label' => 'Garantir vaga',
                'cta_style' => 'primary',
                'cta_url' => 'https://devlab.com.br/react-performance',
                'seats' => 'Vagas disponíveis',
                'seats_low' => false,
            ],
            [
                'date' => '2027-01-16',
                'title' => 'Meetup DevOps BR — Janeiro 2027',
                'type' => 'meetup',
                'org' => 'DevOps Brasil',
                'time' => '15h00 – 18h00',
                'location' => 'Transmissão ao vivo',
                'is_online' => true,
                'status' => 'open',
                'cta_label' => 'Inscrever-se',
                'cta_style' => 'primary',
                'cta_url' => 'https://devopsbr.com.br/meetup',
                'seats' => 'Vagas ilimitadas',
                'seats_low' => false,
            ],
            [
                'date' => '2027-02-13',
                'title' => 'Workshop: SaaS com Laravel do Zero',
                'type' => 'workshop',
                'org' => 'DevLab Brasil',
                'time' => '09h00 – 17h00',
                'location' => 'São Paulo, SP',
                'is_online' => false,
                'status' => 'open',
                'cta_label' => 'Garantir vaga',
                'cta_style' => 'primary',
                'cta_url' => 'https://devlab.com.br/saas-laravel',
                'seats' => '15 vagas',
                'seats_low' => false,
            ],
            [
                'date' => '2027-03-06',
                'title' => 'React Summit Brasil 2027',
                'type' => 'conf',
                'org' => 'GitNation',
                'time' => '09h00 – 18h00',
                'location' => 'São Paulo, SP',
                'is_online' => false,
                'status' => 'open',
                'cta_label' => 'Comprar ingresso',
                'cta_style' => 'primary',
                'cta_url' => 'https://reactsummit.com',
                'seats' => 'Early bird disponível',
                'seats_low' => false,
            ],
            [
                'date' => '2027-04-17',
                'title' => 'Hackathon Open Source Spring 2027',
                'type' => 'hack',
                'org' => 'OpenDevs BR',
                'time' => '08h00 – 22h00',
                'location' => 'Belo Horizonte, MG',
                'is_online' => false,
                'status' => 'open',
                'cta_label' => 'Inscrever equipe',
                'cta_style' => 'primary',
                'cta_url' => 'https://opendevsbr.com.br/hackathon',
                'seats' => '40 equipes disponíveis',
                'seats_low' => false,
            ],
            [
                'date' => '2027-05-08',
                'title' => 'Workshop: Microsserviços com Laravel + RabbitMQ',
                'type' => 'workshop',
                'org' => 'DevOps Academy BR',
                'time' => '09h00 – 17h00',
                'location' => 'Transmissão ao vivo',
                'is_online' => true,
                'status' => 'open',
                'cta_label' => 'Garantir vaga',
                'cta_style' => 'primary',
                'cta_url' => 'https://devopsacademy.com.br/microservicos',
                'seats' => 'Vagas disponíveis',
                'seats_low' => false,
            ],
            [
                'date' => '2027-06-12',
                'title' => 'Laravel Meetup SP — Junho 2027',
                'type' => 'meetup',
                'org' => 'Laravel São Paulo',
                'time' => '14h00 – 17h30',
                'location' => 'São Paulo, SP',
                'is_online' => false,
                'status' => 'open',
                'cta_label' => 'Confirmar presença',
                'cta_style' => 'primary',
                'cta_url' => 'https://meetup.com/laravel-sp',
                'seats' => 'Vagas disponíveis',
                'seats_low' => false,
            ],
            [
                'date' => '2027-07-24',
                'title' => 'TDC Innovation 2027',
                'type' => 'conf',
                'org' => 'The Developer\'s Conference',
                'time' => '08h00 – 18h00',
                'location' => 'São Paulo, SP',
                'is_online' => false,
                'status' => 'open',
                'cta_label' => 'Comprar ingresso',
                'cta_style' => 'primary',
                'cta_url' => 'https://thedevconf.com',
                'seats' => 'Early bird disponível',
                'seats_low' => false,
            ],
            [
                'date' => '2027-09-04',
                'title' => 'Meetup Backend Brasil — Setembro 2027',
                'type' => 'meetup',
                'org' => 'Backend Brasil',
                'time' => '15h00 – 18h00',
                'location' => 'Transmissão ao vivo',
                'is_online' => true,
                'status' => 'open',
                'cta_label' => 'Inscrever-se',
                'cta_style' => 'primary',
                'cta_url' => 'https://backendbrasilmeetup.com.br',
                'seats' => 'Vagas ilimitadas',
                'seats_low' => false,
            ],
        ];

        foreach ($events as $order => $data) {
            Event::create(array_merge($data, [
                'is_active' => true,
                'order' => $order + 1,
            ]));
        }
    }
}
